platform :ios,'7.1'
pod 'AFNetworking'
pod 'SocketRocket'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'AMap2DMap'
pod 'VPImageCropper'
pod 'AMapSearch'
pod 'INTULocationManager'
pod 'KVNProgress'
pod 'RongCloudIMKit'
pod 'MJRefresh', '~> 0.0.1'
pod 'NSDate+TimeAgo'
pod 'NJKWebViewProgress'
pod 'ActionSheetPicker-3.0'
pod 'UMengAnalytics-NO-IDFA'
pod 'UMengMessage'
